---
- name: short-stack
  hosts: all
  roles:
    - core
    - cask
    - command-line-tools
    - osx
    - ruby
    - tmux
    - vim
    - zsh
  tasks:
    - name: ensure osx configuration
      action: "{{ item }}"
      with_items:
      - keyboard_initial_key_repeat_delay
      - keyboard_key_repeat_rate
      - keyboard_repeat_on_keydown
      - finder_show_path_bar
      - finder_show_status_bar
      - finder_airdrop_over_ethernet
      notify:
        - restart dock
        - restart finder
  vars:
    cask:
      - firefox
